if [[ $- != *i* ]]; then
  # Shell is non-interactive.  Be done now!
  return
fi


if command -v tmux &>/dev/null && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
 tmux
fi

export LANG="${LANG:-en_US.UTF-8}"

export DOTFILES_DIR="$HOME/code/personal/dotfiles"
export BASHFILES_DIR="$DOTFILES_DIR/bash"
export BLESH_DIR="$HOME/.local/share/blesh"
export XDG_CONFIG_HOME="$HOME/.config"

# Shell variables
export PAGER=less
export EDITOR=vim

export PATH="$PATH:$HOME/.local/bin:$HOME/.cargo/bin"
export LESS='-R'

# temporary
alias wezterm=k:ome/mjr/code/libraries/wezterm/wezterm-20230712-072601-f4abf8fd/target/release/wezterm


if [ -d /opt/local/bin ]; then
  PATH="/opt/local/bin:$PATH"
fi

if [ -d /usr/lib/cw ]; then
  PATH="/usr/lib/cw:$PATH"
fi

## shopt & set options
shopt -s cdspell                # This will correct minor spelling errors in a cd command.
shopt -s histappend             # Append to history rather than overwrite
shopt -s checkwinsize           # Check window after each command
shopt -s dotglob                # files beginning with . to be returned in the results of path-name expansion.
shopt -s extglob                # use extended globbing
set -o noclobber                # prevent overwriting files with cat
set -o ignoreeof                # stops ctrl+d from logging me out
# unsupported by macos /bin/bash
shopt -s direxpand 2> /dev/null # prevent dir expansion and $ escaping in tab complete
shopt -s globstar  2> /dev/null # ** matches ./ and subdirs recursively. Cannot be used for files

# make the terminal give up control of ctrl-s and ctrl-q
stty -ixon -ixoff
stty stop undef

# vim-mode settings
set -o vi
stty time 0                 # 1/10 s
bind 'set keyseq-timeout 1' #ms
# set -sg escape-time 1 # ms

function _set_user_friendly_aliases {
  case $(uname -s) in
    Darwin | FreeBSD) alias ls="ls -hFG" ;;
    Linux) alias ls="ls --color=always -hF" ;;
    NetBSD | OpenBSD) alias ls="ls -hF" ;;
  esac

  alias rm="rm -i"
  alias mv="mv -i"
  alias cp="cp -i"
  alias mkdir='mkdir -p -v'
  alias df='df -h'
  alias du='du -h -c'
  alias lsd="ls -hdlf */"
  alias ll="ls -hl"
  alias l="ls"

  # vim-mode exit
  alias ":q"="exit"
}
_set_user_friendly_aliases

alias manage_memory="sudo ncdu -e $@"

#shopt -s extdebug; trap "tput sgr0" DEBUG


source "$BASHFILES_DIR/aesthetics.sh"
source "$BASHFILES_DIR/completions.sh"
source "$BASHFILES_DIR/prompt_and_history.sh"
source "$BASHFILES_DIR/utils.sh"
source "$DOTFILES_DIR/vscode/init.sh"

case $(uname -s) in
  Darwin | FreeBSD) source "$DOTFILES_DIR/macos/macos.sh" ;;
  Linux) source "$DOTFILES_DIR/blackbox/blackbox.sh" ;;
esac
