# cargo install starship --locked
# Catppuccin Mocha palette

format = """
$time\
$username\
${custom.dir}\
$git_branch\
$git_status\
$jobs\
[](fg:#1e1e2e bg:#313244) \
"""

# Disable the blank line at the start of the prompt
add_newline = false

[time]
disabled = false
time_format = "%m-%d %R"
style = "fg:#89dceb bg:#1e1e2e"
format = '[ $time ]($style)'

[directory]
truncate_to_repo = false
style = "fg:#cba6f7 bg:#1e1e2e"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
# Order matters (most precise first)
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[docker_context]
symbol = " "
style = "fg:#89dceb bg:#1e1e2e"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "fg:#f9e2af bg:#1e1e2e"
format = '[$branch ]($style)'

[git_status]
style = "fg:#f9e2af bg:#1e1e2e"
format = '[$all_status$ahead_behind ]($style)'

[git_metrics]
disabled = true
added_style = "#a6e3a1"

[nodejs]
symbol = ""
style = "fg:#89b4fa bg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#f38ba8 bg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[python]
version_format = 'py$major.$minor'
style = "fg:#cdd6f4 bg:#1e1e2e"
format = '[$virtualenv ]($style)'
detect_files = []
detect_extensions = [ ]

[jobs]
style = "fg:#89b4fa bg:#1e1e2e"
symbol = "&"
format = '[$number$symbol ]($style)'

[custom.dir]
when = true
shell = ["bash", "--noprofile", "--norc"]
style = "fg:#cba6f7 bg:#1e1e2e"
command = '''
short_path() {
  if [[ $PWD == $HOME ]]; then
    echo "~"
  else
    # Replace the home directory part
    _dir=$(echo "$PWD" | sed "s|$HOME|~|g")

    # Define a regex to match directory names with more than three characters
    more_than_three_chars='/\([^/][^/][^/]\)[^/]\+'

    # Use sed to replace the long names with their three-character short versions
    dir=$(echo "$_dir" | sed "s|$more_than_three_chars|/\1|g")

    # Print the final, plain-text path
    echo "$dir"
  fi
};
short_path
'''
format = "[$output ]($style)"
