# cargo install starship --locked
# Catppuccin Mocha palette via official integration

palette = "catppuccin_mocha"

format = """
$time\
$username\
${custom.dir}\
$git_branch\
$git_status\
$jobs\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[time]
disabled = false
time_format = "%m-%d %R"
style = "sky"
format = '[$time ]($style)'

[directory]
truncate_to_repo = false
style = "mauve"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
# Order matters (most precise first)
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[docker_context]
symbol = " "
style = "teal"
format = '[$symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "yellow"
format = '[$branch ]($style)'

[git_status]
style = "yellow"
format = '[$all_status$ahead_behind ]($style)'

[git_metrics]
disabled = true
added_style = "green"

[nodejs]
symbol = ""
style = "blue"
format = '[$symbol ($version) ]($style)'

[rust]
symbol = ""
style = "red"
format = '[$symbol ($version) ]($style)'

[python]
version_format = 'py$major.$minor'
style = "text"
format = '[$virtualenv ]($style)'
detect_files = []
detect_extensions = [ ]

[jobs]
style = "blue"
symbol = "&"
format = '[$number$symbol ]($style)'

[custom.dir]
when = true
shell = ["bash", "--noprofile", "--norc"]
style = "mauve"
command = '''
short_path() {
  if [[ $PWD == $HOME ]]; then
    echo "~"
  else
    # Replace the home directory part
    _dir=$(echo "$PWD" | sed "s|$HOME|~|g")

    # Define a regex to match directory names with more than three characters
    more_than_three_chars='/\([^/][^/][^/]\)[^/]\+'

    # Use sed to replace the long names with their three-character short versions
    dir=$(echo "$_dir" | sed "s|$more_than_three_chars|/\1|g")

    # Print the final, plain-text path
    echo "$dir"
  fi
};
short_path
'''
format = "[$output ]($style)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
